AcunMedyaPortfolyo/Controllers/AdminLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AcunMedyaPortfolyo.Controllers
{
    public class AdminLayoutController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult PartialHead()
        {
            return PartialView("PartialHead");
        }
        public ActionResult PartialMenu()
        {
            return PartialView("PartialMenu");
        }
        public ActionResult PartialScript()
        {
            return PartialView("PartialScript");
        }
    }
}

AcunMedyaPortfolyo/Views/AdminLayout/Index.cshtml
<!doctype html>
<html lang="en">

@Html.Action("PartialHead", "AdminLayout")

<body>
    <div class="wrapper d-flex align-items-stretch">
        <nav style="background-color:midnightblue" id="sidebar" class="active">
            <div class="custom-menu" style="background-color:midnightblue">
                <button type="button" id="sidebarCollapse" class="btn btn-primary"style="background-color:midnightblue">
                    <i class="fa fa-bars" style="background-color:midnightblue"></i>
                </button>
            </div>
            <div class="p-4" style="background-color:aliceblue">
                <h1><a href="index.html" class="logo" style="background-color:midnightblue">Flash</a></h1>

            @Html.Action("PartialMenu", "AdminLayout")


            <div class="mb-5">
                <h3 class="h6 mb-3" style="background-color:midnightblue"  >Subscribe for newsletter</h3>
                <form action="#" class="subscribe-form">
                    <div class="form-group d-flex">
                        <div style="background-color:midnightblue" class="icon"><span class="icon-paper-plane"></span></div>
                        <input type="text" class="form-control" placeholder="Enter Email Address" style="background-color: midnightblue">
                    </div>
                </form>
            </div>

                <div class="footer">
                    <p style="background-color:midnightblue">
                        Copyright &copy;
                        <script >document.write(new Date().getFullYear());</script > All rights reserved | This template is made with <i  class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
                    </p>
                </div>
            </div>
        </nav>

        <!-- Page Content -->
        <div id="content" class="p-4 p-md-5 pt-5">
            @RenderBody()


        </div>
    </div>

@Html.Action("PartialScript", "AdminLayout")

</body>
</html>